### PR TITLE
adding new calendar + misc fixes

### LINKED ISSUE #1: Add Philoptochos calendar

### PR DESCRIPTION
**Pull request by amilios**
this should resolve #1

### CODE REVIEW

File: src/components/Events.vue [hunk 1]
```diff
@@ -10,9 +10,9 @@
               <h5 class="mb-1">{{ extractDayMonth(event) }}</h5>
               <p v-if="isSameDayEvent(event)">{{ extractSingleDayTime(event) }}</p>
             </div>
-            <div class="d-flex w-100 justify-content-between">
+            <div class="d-flex w-100 justify-content-sm-between flex-sm-row flex-column">
               <p class="mb-1">{{ event.summary }}</p>
-              <small>{{ removeDomain(event.creator.email) }}</small>
+              <small>{{ event.creator.email }}</small>
```
Comment (evangelos-com) [inline src/components/Events.vue:15]: Good stuff, thank you 👍

**Review by evangelos-com — APPROVED** [review]
